export const plan = [
  {
    name: "5G 시그니처",
    month_price: 130000,
    data: "무제한",
    data_plus: "",
    share_data: "60GB+60GB",
    share_data_plus: "+참 쉬운 가족 데이터 50GB",
    voice: "집/이동전화 무제한",
    voice_plus: "+부가통화 300분",
    message: "기본제공",
    smart_device: "2회선",
    smart_device_discount: "회선 당 최대 11,000원 할인",
    premiun_service: "카테고리 팩",
    basic_benefit: "U+ 모바일tv 무료",
    family_sig5g: "33,000원",
    telecom_tech: 3,
    plan_type: 2,
  },
  {
    name: "5G 프리미어 슈퍼",
    month_price: 115000,
    data: "무제한",
    data_plus: "",
    share_data: "50GB+50GB",
    share_data_plus: "+참 쉬운 가족 데이터 50GB",
    voice: "집/이동전화 무제한",
    voice_plus: "+부가통화 300분",
    message: "기본제공",
    smart_device: "2회선",
    smart_device_discount: "회선 당 최대 11,000원 할인",
    premiun_service: "카테고리 팩",
    basic_benefit: "U+ 모바일tv 무료",
    family_sig5g: "",
    telecom_tech: 3,
    plan_type: 2,
  },
  {
    name: "5G 프리미어 플러스",
    month_price: 105000,
    data: "무제한",
    data_plus: "",
    share_data: "50GB+50GB",
    share_data_plus: "",
    voice: "집/이동전화 무제한",
    voice_plus: "+부가통화 300분",
    message: "기본제공",
    smart_device: "2회선",
    smart_device_discount: "회선 당 최대 11,000원 할인",
    premiun_service: "",
    basic_benefit: "",
    family_sig5g: "",
    telecom_tech: 2,
    plan_type: 2,
  },
];

export const phone = [
  {
    phoneId: 1,
    titleName: "갤럭시 A33 5G",
    titleSub: "(갤럭시워치5) 5G 다이렉트 65",
    model: "SM-A336N",
    price: 499400,
    previewImg:
      "https://image.lguplus.com/static/pc-contents/images/prdv/20220729-094817-735-tXO0PeyD.jpg",
    manufacturingCompany: "삼성",
    telecomTech: "5G",
    phoneInfo: {
      phoneInfoId: 1,
      cpu: "5nm AP, Octa Core, Exynos 1280",
      display: '6.4"(164.0 mm) FHD+ Super AMOLED',
      size: "159.7 x 74.0 x 8.1mm",
      weight: "186g",
      camera:
        "메인 48MP(F1.8) AF OIS, 초광각 8MP(F2.2) 심도 2MP(F2.4), 접사 5MP(F2.4)",
      memory:
        "RAM 6GB + 내장 메모리 128GB (외장 메모리 슬롯 지원 최대 1TB (별매)",
      storage: "5,000mAh",
      waterproof: "IP67",
      colorList: ["퓨어 레드", "퓨어 그린"],
    },
    colorList: [
      {
        colorId: 1,
        name: "퓨어 레드",
        hexCode: "#ff0000",
      },
      {
        colorId: 3,
        name: "퓨어 그린",
        hexCode: "#008000",
      },
    ],
  },
  {
    phoneId: 2,
    titleName: "iPhone SE 64GB 3세대",
    titleSub: "(애플워치SE) 5G 다이렉트 65",
    model: "A2783-64",
    price: 589600,
    previewImg:
      "https://image.lguplus.com/common/images/hphn/product/A2783-64/list/ushop_A2783-64_67_A20220317110612311.jpg",
    manufacturingCompany: "애플",
    telecomTech: "5G",
    phoneInfo: {
      phoneInfoId: 2,
      cpu: "A15 Bioninc 칩",
      display: "4.7형 Retina HD 디스플레이",
      size: "138.4 x 67.3 x 7.3 mm",
      weight: "144g",
      camera: "싱글 12MP 와이드 카메라(와이드)",
      memory: "64GB",
      storage:
        "동영상 재생 : 최대 15시간, 스트리밍 최대 10시간 / 오디오 재생 : 최대 50시간",
      waterproof: "IP67 (최대 수심 1m, 최대 30분)",
      colorList: ["퓨어 블루"],
    },
    colorList: [
      {
        colorId: 2,
        name: "퓨어 블루",
        hexCode: "#0000ff",
      },
    ],
  },
];
