export const plan = [
  {
    name: "5G 시그니처",
    month_price: 130000,
    data: "무제한",
    data_plus: "",
    share_data: "60GB+60GB",
    share_data_plus: "+참 쉬운 가족 데이터 50GB",
    voice: "집/이동전화 무제한",
    voice_plus: "+부가통화 300분",
    message: "기본제공",
    smart_device: "2회선",
    smart_device_discount: "회선 당 최대 11,000원 할인",
    premiun_service: "카테고리 팩",
    basic_benefit: "U+ 모바일tv 무료",
    family_sig5g: "33,000원",
    telecom_tech: 3,
    plan_type: 2,
  },
  {
    name: "5G 프리미어 슈퍼",
    month_price: 115000,
    data: "무제한",
    data_plus: "",
    share_data: "50GB+50GB",
    share_data_plus: "+참 쉬운 가족 데이터 50GB",
    voice: "집/이동전화 무제한",
    voice_plus: "+부가통화 300분",
    message: "기본제공",
    smart_device: "2회선",
    smart_device_discount: "회선 당 최대 11,000원 할인",
    premiun_service: "카테고리 팩",
    basic_benefit: "U+ 모바일tv 무료",
    family_sig5g: "",
    telecom_tech: 3,
    plan_type: 2,
  },
  {
    name: "5G 프리미어 플러스",
    month_price: 105000,
    data: "무제한",
    data_plus: "",
    share_data: "50GB+50GB",
    share_data_plus: "",
    voice: "집/이동전화 무제한",
    voice_plus: "+부가통화 300분",
    message: "기본제공",
    smart_device: "2회선",
    smart_device_discount: "회선 당 최대 11,000원 할인",
    premiun_service: "",
    basic_benefit: "",
    family_sig5g: "",
    telecom_tech: 2,
    plan_type: 2,
  },
];
